### ISSUE TITLE
UI of Hawkbit-device Simulator

### ISSUE THREAD

**Issue by shailesharya** [eclipse/hawkbit-examples#44]
I have succussfully build the Hawkbit Simulator from the source and the simulator is running but my concern is I'm not having the UI to create the simulate devices. 
I'm attaching the screen shot for the referance.
![Screenshot at 2020-04-21 23-52-57](https://user-images.githubusercontent.com/41483772/79900052-4425a780-842b-11ea-9f61-8accc60facee.png)

Please help me with the same. 
Thank you.

**Comment by schabdo** [comment]
The simulator is not offering any UI. Simulator is configured/controlled by properties or HTTP calls. So simulator is just responding e.g. a call to `/start` within your browser will start the simulation. You'll find all the possible "commands" and parameters within the class `SimulationController` e.g. for `/start` have a look [here](https://github.com/eclipse/hawkbit-examples/blob/master/hawkbit-device-simulator/src/main/java/org/eclipse/hawkbit/simulator/SimulationController.java#L81)

**Comment by GittyDan** [comment]
In this YT Video from 2018 https://youtu.be/8vcLXs9lc-4?t=1804 "Software Updates in IoT with Eclipse hawkBit" there is a UI on the simulator. was it removed since than?

![grafik](https://user-images.githubusercontent.com/44602915/163993617-a50430d9-6033-4c1b-85f1-08621cd548ad.png)

**Comment by marcusx** [comment]
Was removed in https://github.com/eclipse/hawkbit-examples/pull/8 what a shame. There is only a REST API left.

 I found some documentation in the readme: https://github.com/eclipse/hawkbit-examples/blob/master/hawkbit-device-simulator/README.md
And here https://docs.bosch-iot-suite.com/rollouts/Rollouts-service-integration-with-hawkBit-device-simulator-running-on-Cloud-Foundry.html
