### ISSUE TITLE
Faulty jar file?

### ISSUE THREAD

**Issue by PotatoeCrisp** [eclipse/hawkbit-examples#61]
hawkbit-example-mgmt-simulator-#version#-SNAPSHOT.jar
That file seems to have an issue:
"no main manifest attribute, in ./hawkbit-example-mgmt-simulator/target/hawkbit-example-mgmt-simulator-0.3.0-SNAPSHOT.jar"

**Comment by tonyjackson-srt** [comment]
+1 here with latest master

`no main manifest attribute, in ./hawkbit-example-mgmt-simulator/target/hawkbit-example-mgmt-simulator-0-SNAPSHOT.jar`

Nearly two years and no reply to this issue?  I am not thinking this makes it a good choice for our deployment.
